spring:
  datasource:
    url: jdbc:postgresql://web-production-9565.up.railway.app:5432/railway?user=${PGUSER}&password=${PGPASSWORD}&sslmode=require&connectTimeout=30000
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
