spring:
  datasource:
    url: jdbc:postgresql://<your-database-host>.railway.app:5432/railway?user=${PGUSER}&password=${PGPASSWORD}&sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate