spring:
  datasource:
    url: jdbc:postgresql://caboose.proxy.rlwy.net:20908/railway?user=${PGUSER}&password=${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
